name = "cf-workers-status-page"
main = "./index.js"
workers_dev = false
account_id = "fbe0b9bc03cff1c4c6f6066090cb35e6"
#type = "webpack"
#webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2025-03-21"

[triggers]
crons = ["*/15 * * * *"]

#[site]
#bucket = "out"
#entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
#zone_id="xxx"
#route="xxx"
